"""Canonical metric names recorded by both algorithms."""

METRICS = (
    "pass_at_1",
    "pass_at_4",
    "gsm8k_accuracy",
    "math500_accuracy",
    "math_level_1_accuracy",
    "math_level_2_accuracy",
    "math_level_3_accuracy",
    "math_level_4_accuracy",
    "math_level_5_accuracy",
    "format_accuracy",
    "parse_success_rate",
    "valid_expression_rate",
    "number_usage_accuracy",
    "reward",
    "generated_tokens",
    "completions",
    "kl",
    "entropy",
    "ppo_value_loss",
    "ppo_explained_variance",
    "grpo_zero_variance_group_rate",
    "completion_length",
    "wall_time",
    "peak_vram",
    "gpu_hours",
    "estimated_cost_cny",
)
